steps:
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['run', 'build']
    secretEnv: ['CMS_API_KEY']
availableSecrets:
  secretManager:
    - versionName: projects/132176856044/secrets/CMS_API_KEY
      env: 'CMS_API_KEY'
