services:
  backend:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:16.9
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp_development
    ports:
      - "5432:5432"

volumes:
  bundle:
  postgres:

